/* ==================================================================== *
 *  Archives of Nethys links
 *
 *  Pathbuilder gives us names and nothing else — no ids, no slugs — so
 *  every AoN link on a character sheet has to be resolved from the name.
 *  src/data/aon-index.json (regenerated by tools/fetch-aon-index.mjs) is a
 *  name -> page-url map per kind of thing; it's loaded lazily the first
 *  time a sheet is opened so it never weighs on initial page load.
 *
 *  aonUrl() ALWAYS returns a url. If the index hasn't loaded yet, or the
 *  name isn't in it, the link falls back to an AoN search for that name —
 *  so nothing on the sheet is ever a dead link.
 * ==================================================================== */

export const AON_BASE = "https://2e.aonprd.com";

/* Both the generator and the lookup key on this, so a name can never be
 * written one way and queried another. */
export const normalize = (s) => String(s || "").trim().replace(/\s+/g, " ").toLowerCase();

export const aonSearchUrl = (name) => `${AON_BASE}/Search.aspx?q=${encodeURIComponent(name)}`;

/* ---- the index (lazy, mirrors loadCreatures in combatants.js) ---- */
let _cache = null;
let _promise = null;
// Synchronous peek at the loaded index (null until loadAonIndex resolves).
export const cachedAonIndex = () => _cache;
export function loadAonIndex() {
  if (_cache) return Promise.resolve(_cache);
  if (!_promise) {
    _promise = import("../data/aon-index.json").then((m) => {
      _cache = m.default;
      return _cache;
    });
  }
  return _promise;
}

/* ---- name repair ----
 * Pathbuilder shows an item by its decorated display name ("+1 striking
 * rapier", "cold iron (low-grade) dagger"); AoN indexes the base item. Every
 * decoration in PF2e is a prefix or a parenthetical, so the base item is
 * always the tail — try the name as written, then peel from the front. */
const RUNE = /^(?:(?:greater|major|true)\s+)?(?:striking|resilient|potency|shadow|ghost touch)\s+/;
const PARENS = /\s*\([^)]*\)/g; // "cold iron (low-grade) dagger" -> "cold iron dagger"
const MAX_PEEL = 4; // never peel so far that a common word alone could match

function stripRunes(n) {
  let s = n.replace(/^\+\d+\s+/, "");
  let prev;
  do {
    prev = s;
    s = s.replace(RUNE, "");
  } while (s !== prev);
  return s;
}

function itemVariants(n) {
  const out = [];
  const add = (v) => {
    const s = v.trim().replace(/\s+/g, " ");
    if (s && !out.includes(s)) out.push(s);
  };
  // The name as written wins, so an item AoN really does list under its full
  // decorated name ("healing potion (lesser)") is never peeled past.
  for (const base of [n, stripRunes(n)]) {
    add(base);
    add(base.replace(PARENS, ""));
  }
  for (const base of [...out]) {
    const words = base.split(" ");
    for (let i = 1; i <= Math.min(MAX_PEEL, words.length - 1); i++) add(words.slice(i).join(" "));
  }
  return out;
}

/* ---- resolution ----
 * Returns the AoN page url for a name, or null when we can't place it.
 * `kind` is a group in the index; "classFeature" additionally takes the
 * character's class, because AoN has no page per class feature — the
 * entries all point at the class page, and the same feature name (e.g.
 * "Skill Increases") appears under nearly every class.
 *
 * The index is a parameter so this stays pure and can be exercised outside
 * the browser (the aon-index.json import only resolves under a bundler);
 * aonLookup below is the cached-index wrapper the app actually calls. */
export function resolveAonUrl(idx, kind, name, opts = {}) {
  const n = normalize(name);
  if (!idx || !n) return null;
  const hit = (group, key) => (idx[group] ? idx[group][key] : undefined);

  let url;
  if (kind === "feat" || kind === "classFeature") {
    // Pathbuilder files heritages and class/ancestry features into the same
    // two lists as feats, so both kinds try every place such a name can live —
    // only the order differs. AoN has no page per class feature, so those
    // entries point at the class page and need the character's class to pick
    // the right one ("Skill Increases" exists under nearly every class).
    const cls = normalize(opts.cls);
    const asFeature = () => (cls ? hit("classFeature", `${cls}|${n}`) : undefined);
    url =
      kind === "feat"
        ? hit("feat", n) || hit("heritage", n) || hit("ancestry", n) || asFeature()
        : asFeature() || hit("feat", n) || hit("heritage", n) || hit("ancestry", n);
  } else if (kind === "item") {
    for (const v of itemVariants(n)) {
      url = hit("item", v);
      if (url) break;
    }
  } else {
    url = hit(kind, n);
  }
  return url ? AON_BASE + url : null;
}

export const aonLookup = (kind, name, opts) => resolveAonUrl(_cache, kind, name, opts);

export function aonUrl(kind, name, opts) {
  return aonLookup(kind, name, opts) || aonSearchUrl(name);
}
