/* ==================================================================== *
 *  Bestiary loaders (browser / Vite only)
 *
 *  Lazy loaders for the Archives-of-Nethys creature list and the sharded
 *  stat blocks. Split out of combatants.js because they rely on Vite's
 *  import.meta.glob and JSON dynamic imports, which keeps combatants.js
 *  importable from plain Node (the MCP server reuses its factories).
 * ==================================================================== */
import { statBlockShard, creatureKey, normalizeStatBlock, isEmptyStatBlock } from "./statblock.js";

/* ---- standard creatures (Archives of Nethys data) ----
 * The bestiary lives in src/data/creatures.json (regenerated by
 * tools/fetch-creatures.mjs). It's loaded lazily the first time the creature
 * palette opens so it never weighs on initial page load. */
let _creatureCache = null;
let _creaturePromise = null;
// Synchronous peek at the loaded bestiary (null until loadCreatures resolves);
// lets the palette seed initial state without a flash when reopened.
export const cachedCreatures = () => _creatureCache;
export function loadCreatures() {
  if (_creatureCache) return Promise.resolve(_creatureCache);
  if (!_creaturePromise) {
    _creaturePromise = import("../data/creatures.json").then((m) => {
      _creatureCache = m.default;
      return _creatureCache;
    });
  }
  return _creaturePromise;
}

/* ---- bestiary stat blocks ----
 * Strikes, abilities and spells for the bestiary live in src/data/statblocks/,
 * sharded by AoN id (see tools/fetch-creatures.mjs), so a creature's block costs
 * one ~100 KB fetch rather than the whole 3 MB. A block found this way is copied
 * onto the combatant: from then on the card needs no network at the table. */
const _shardLoaders = import.meta.glob("../data/statblocks/*.json");
const _shards = new Map(); // shard name -> promise of { [aonId]: block }
function loadShard(name) {
  if (!_shards.has(name)) {
    const load = _shardLoaders[`../data/statblocks/${name}.json`];
    _shards.set(name, load ? load().then((m) => m.default).catch(() => ({})) : Promise.resolve({}));
  }
  return _shards.get(name);
}
export async function loadBestiaryStatBlock(aonId) {
  if (aonId == null) return null;
  const sb = (await loadShard(statBlockShard(aonId)))[aonId];
  return isEmptyStatBlock(sb) ? null : normalizeStatBlock(sb, "bestiary");
}
/* The fallback for a creature that didn't come from the palette — a scenario
 * creature the adventure gives no stat block for, say. Exact name only: a near
 * miss would put the wrong creature's attacks in front of the GM. */
export async function findBestiaryStatBlock(name) {
  const key = creatureKey(name);
  if (!key) return null;
  const hit = (await loadCreatures()).find((cr) => cr.name.toLowerCase() === key);
  return hit ? loadBestiaryStatBlock(hit.id) : null;
}
