/* ==================================================================== *
 *  Combatant builders + bestiary loading
 *
 *  Factories that turn PCs, scenario NPCs, and Archives-of-Nethys creature
 *  records into encounter combatants, the lazy bestiary loader, and the
 *  scenario-encounter prefill / map-seeding helpers.
 * ==================================================================== */
import { uid } from "./pf2e.js";
import { AON_BASE } from "./aon.js";

export function combatantFromPc(pc) {
  const sv = (k) => (pc.saves.find((s) => s.key === k) || {}).total || 0;
  return {
    id: uid(),
    name: pc.name,
    kind: "pc",
    level: pc.level,
    init: null,
    maxHp: pc.hp,
    hp: pc.hp,
    ac: (pc.ac && pc.ac.acTotal) || 10,
    perception: (pc.perception && pc.perception.total) || 0,
    fort: sv("fortitude"),
    ref: sv("reflex"),
    will: sv("will"),
    conditions: [],
    pcId: pc.id,
    notes: "",
  };
}

export function combatantFromNpc(npc) {
  return {
    id: uid(),
    name: npc.name,
    kind: "ally",
    level: npc.level == null ? 0 : npc.level,
    init: null,
    maxHp: npc.hp,
    hp: npc.hp,
    ac: npc.ac,
    perception: npc.perception,
    fort: npc.fort == null ? 0 : npc.fort,
    ref: npc.ref == null ? 0 : npc.ref,
    will: npc.will == null ? 0 : npc.will,
    conditions: [],
    pcId: null,
    npcId: npc.id,
    notes: "",
  };
}

/* ---- standard creatures (Archives of Nethys data) ----
 * The bestiary lives in src/data/creatures.json (regenerated by
 * tools/fetch-creatures.mjs). It's loaded lazily the first time the creature
 * palette opens so it never weighs on initial page load. */
let _creatureCache = null;
let _creaturePromise = null;
// Synchronous peek at the loaded bestiary (null until loadCreatures resolves);
// lets the palette seed initial state without a flash when reopened.
export const cachedCreatures = () => _creatureCache;
export function loadCreatures() {
  if (_creatureCache) return Promise.resolve(_creatureCache);
  if (!_creaturePromise) {
    _creaturePromise = import("../data/creatures.json").then((m) => {
      _creatureCache = m.default;
      return _creatureCache;
    });
  }
  return _creaturePromise;
}

// Turn a standard creature record into an enemy combatant, carrying its AoN id
// + page url so the card's ↗ link can open the Archives of Nethys entry.
export function combatantFromCreature(cr) {
  return {
    id: uid(),
    name: cr.name,
    kind: "enemy",
    level: cr.level,
    init: null,
    maxHp: cr.hp,
    hp: cr.hp,
    ac: cr.ac,
    perception: cr.per,
    fort: cr.fort,
    ref: cr.ref,
    will: cr.will,
    conditions: [],
    pcId: null,
    notes: "",
    aon: cr.id,
    aonUrl: AON_BASE + cr.url,
  };
}

/* ---- prefill: encounters + creature stats transcribed from the
 *      scenario PDF appendix (The Second Confirmation). Each area is a
 *      "pick one option" table, so one of each option is loaded; trim or
 *      duplicate to the rolled result. ---- */
/* SCENARIO_ENCOUNTERS: loaded at runtime from the scenario data layer */

/* Encounter maps live in the scenario data (keyed by encounter name). We seed
 * them onto encounters at load/prefill so persisted encounters always show their
 * map, and strip them before persisting so the overlay isn't bloated with the
 * (already-in-scenario) image — the map is rehydrated from the scenario on the
 * next load. A user's own uploaded map (different from the scenario map) is
 * preserved and persisted. */
// Build the name -> map lookup from the active scenario's encounters.
function scenEncMap(scenEnc) {
  return (scenEnc || []).reduce((m, e) => {
    if (e.map) m[e.name] = e.map;
    return m;
  }, {});
}
export function seedEncounterMaps(list, scenEnc) {
  const sm = scenEncMap(scenEnc);
  return list.map((e) => (!e.map && sm[e.name] ? { ...e, map: sm[e.name] } : e));
}
export function stripSeededMaps(list, scenEnc) {
  const sm = scenEncMap(scenEnc);
  return list.map((e) => (sm[e.name] && e.map === sm[e.name] ? { ...e, map: "" } : e));
}

export function buildScenarioEncounters(existingNames, scenEnc) {
  return (scenEnc || []).filter((e) => !existingNames.has(e.name)).map((e) => ({
    id: uid(),
    name: e.name,
    note: e.note || "",
    map: e.map || "",
    combatants: e.creatures.map((c) => ({
      id: uid(),
      name: c.name,
      kind: c.kind || "enemy",
      level: c.level,
      init: null,
      maxHp: c.hp,
      hp: c.hp,
      ac: c.ac,
      perception: c.perception,
      fort: c.fort,
      ref: c.ref,
      will: c.will,
      conditions: [],
      pcId: null,
      npcId: c.npcId || null,
      notes: c.qty && c.qty > 1 ? `run ×${c.qty}` : "",
    })),
  }));
}
