/* ==================================================================== *
 *  Animal companions
 *
 *  Pathbuilder tells us which animal a companion is, how far it's been
 *  advanced, what specialization it took and whether it's wearing barding —
 *  but none of its numbers, because a companion's numbers aren't printed
 *  anywhere: they're derived from its type's base stat block, its owner's
 *  level, and each advancement applied in turn.
 *
 *  So: src/data/companions.json holds the base stat blocks (regenerated by
 *  tools/fetch-companions.mjs), parsePet() reads what Pathbuilder gives us,
 *  and companionStatblock() does the advancement math.
 *
 *  Rules: Player Core pp. 206, 211 (young / mature / nimble / savage /
 *  specialized), World Guide p. 117 (indomitable megafauna), and the barding
 *  table in Player Core p. 295.
 * ==================================================================== */
import { SKILLS, sign } from "./pf2e.js";

/* ---- the base stat blocks (lazy, mirrors loadCreatures in combatants.js) ---- */
let _cache = null;
let _promise = null;
// Synchronous peek at the loaded data (null until loadCompanions resolves).
export const cachedCompanions = () => _cache;
export function loadCompanions() {
  if (_cache) return Promise.resolve(_cache);
  if (!_promise) {
    _promise = import("../data/companions.json").then((m) => {
      _cache = m.default;
      return _cache;
    });
  }
  return _promise;
}

const norm = (s) => String(s || "").trim().toLowerCase();

// Look a species up by name ("Bear" -> the Bear stat block).
export function companionBase(species, data = _cache) {
  if (!data || !species) return null;
  const n = norm(species);
  return data.types.find((t) => norm(t.name) === n) || null;
}

export function specializationInfo(name, data = _cache) {
  if (!data || !name) return null;
  const n = norm(name);
  return data.specializations.find((s) => norm(s.name) === n) || null;
}

/* ---- reading a Pathbuilder pet ----
 * build.pets[] holds animal companions AND familiars; build.familiars is left
 * empty. An animal companion looks like:
 *   { type: "Animal Companion", name: "Galador - Mature Bear", animal: "Bear",
 *     mature: true, incredible: false, incredibleType: "Nimble",
 *     specializations: [], armor: "Barding, Heavy", equipment: [] }
 * Pathbuilder appends "<tier> <animal>" to whatever the player named it, so the
 * given name is the part before the last " - ". */
export function parsePet(p = {}) {
  const type = String(p.type || "");
  const equipment = (p.equipment || []).map((e) =>
    Array.isArray(e) ? { name: e[0], qty: Number(e[1] || 1) } : { name: String(e), qty: 1 }
  );

  if (/familiar/i.test(type)) {
    return {
      kind: "familiar",
      name: p.name || p.specific || "familiar",
      species: p.specific || null,
      abilities: p.abilities || [],
      equipment,
    };
  }
  if (!/animal companion/i.test(type)) {
    return { kind: "other", name: p.name || type || "companion", equipment };
  }

  const species = p.animal || null;
  const full = String(p.name || species || "companion");
  const cut = full.lastIndexOf(" - ");
  const specializations = (p.specializations || []).filter(Boolean);
  const incredible = p.incredible ? norm(p.incredibleType) || "nimble" : null;
  // A specialized companion is always mature + incredible first, but don't
  // trust that — take mature as implied by anything past it.
  const mature = !!p.mature || !!incredible || specializations.length > 0;

  return {
    kind: "companion",
    name: cut > 0 ? full.slice(0, cut) : full,
    species,
    mature,
    incredible,
    specializations,
    tier: specializations.length ? "specialized" : incredible || (mature ? "mature" : "young"),
    barding: bardingOf(p.armor),
    equipment,
  };
}

/* ---- barding (Player Core p. 295) ---- */
const BARDING = {
  none: { key: "none", label: "unarmored", ac: 0, dexCap: Infinity, check: 0, speed: 0 },
  light: { key: "light", label: "light barding", ac: 1, dexCap: 5, check: -1, speed: -5 },
  heavy: { key: "heavy", label: "heavy barding", ac: 3, dexCap: 3, check: -3, speed: -10 },
};
function bardingOf(armor) {
  const a = norm(armor);
  if (/heavy/.test(a)) return BARDING.heavy;
  if (/light/.test(a) || /barding/.test(a)) return BARDING.light;
  return BARDING.none;
}

/* ---- proficiency ---- */
const RANK_NAME = { 0: "untrained", 2: "trained", 4: "expert", 6: "master", 8: "legendary" };
export const rankName = (r) => RANK_NAME[r] || "untrained";

// pf2e.js imports parsePet from here, so this module can be evaluated while
// pf2e.js is still initializing — build the table on first use rather than at
// import time, when the SKILLS binding may not be live yet.
let _skillAb = null;
const skillAb = () => (_skillAb ||= Object.fromEntries(SKILLS));

const SIZES = ["tiny", "small", "medium", "large", "huge", "gargantuan"];

// "Medium or Large" -> "Large" (each part that's Medium or smaller grows once).
function growSize(size) {
  if (!size) return size;
  const parts = size.split(/\s+or\s+/i).map((p) => {
    const i = SIZES.indexOf(norm(p));
    return i >= 0 && i <= SIZES.indexOf("medium") ? SIZES[i + 1] : norm(p);
  });
  const uniq = [...new Set(parts)];
  return uniq.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join(" or ");
}

/* ---- specializations (Player Core p. 211 and later books) ----
 * `bump` is "increase to expert, or master if it was already expert"; `set` is
 * an absolute rank. Everything here is on top of the generic specialized
 * benefits applied in companionStatblock. */
const SPECIALIZATIONS = {
  ambusher: { mods: { dex: 1 }, bump: { stealth: 4 }, set: { unarmored: 4 } },
  bully: { mods: { str: 1, cha: 3 }, bump: { athletics: 4, intimidation: 4 } },
  daredevil: { mods: { dex: 1 }, set: { acrobatics: 6, unarmored: 4 } },
  "deep diver": { mods: { con: 1 }, set: { athletics: 6, barding: 4 } },
  racer: { mods: { con: 1 }, set: { fortitude: 8 } },
  shade: { set: { unarmored: 4 } },
  "steadfast strider": { mods: { str: 1 }, set: { barding: 4 } },
  tracker: { mods: { wis: 1 }, bump: { survival: 4 } },
  "wildfire scorcher": { mods: { dex: 1 }, set: { reflex: 8, unarmored: 4 } },
  "wind chaser": { mods: { dex: 1 }, set: { acrobatics: 6, reflex: 8, unarmored: 4 } },
  wrecker: { mods: { str: 1 }, set: { athletics: 6 } },
};

/* ---- the actual math ----
 * Returns null when we have no base stat block for the species (an unknown
 * animal, or companions.json not loaded yet) so callers can fall back to
 * showing just what Pathbuilder gave us. */
export function companionStatblock(pet, base, pcLevel, data = _cache) {
  if (!pet || pet.kind !== "companion" || !base) return null;
  const level = Number(pcLevel || 1);

  const mods = { ...base.mods };
  const ranks = {};
  const set = (k, r) => { ranks[k] = Math.max(ranks[k] || 0, r); };
  const bump = (k, r) => set(k, (ranks[k] || 0) >= r ? r + 2 : r);
  const addMods = (m) => Object.entries(m || {}).forEach(([k, v]) => (mods[k] += v));

  // Young: the starting proficiencies every companion has.
  ["unarmed", "unarmored", "barding", "fortitude", "reflex", "will", "perception", "acrobatics", "athletics"]
    .forEach((k) => set(k, 2));
  const typeSkills = (base.skill || []).map(norm).filter((s) => skillAb()[s]);
  typeSkills.forEach((s) => set(s, 2));

  let size = base.size;
  let dice = 1;
  let flat = 0;
  let magical = false;

  if (pet.mature) {
    addMods({ str: 1, dex: 1, con: 1, wis: 1 });
    size = growSize(size);
    ["perception", "fortitude", "reflex", "will"].forEach((k) => set(k, 4));
    // Trained in these three — expert instead if the type was already trained in one.
    ["intimidation", "stealth", "survival"].forEach((k) => set(k, typeSkills.includes(k) ? 4 : 2));
    dice = 2;
  }

  if (pet.incredible === "nimble") {
    addMods({ dex: 2, str: 1, con: 1, wis: 1 });
    set("acrobatics", 4);
    flat = 2;
    magical = true;
  } else if (pet.incredible === "savage") {
    addMods({ str: 2, dex: 1, con: 1, wis: 1 });
    size = growSize(size);
    set("athletics", 4);
    flat = 3;
    magical = true;
  } else if (pet.incredible === "indomitable") {
    addMods({ con: 2, str: 1, dex: 1, wis: 1 });
    size = growSize(size);
    set("athletics", 4);
    set("barding", 4);
    flat = 3;
    magical = true;
  }

  const specs = [];
  if (pet.specializations.length) {
    addMods({ dex: 1, int: 2 });
    set("unarmed", 4);
    ["fortitude", "reflex", "will", "perception"].forEach((k) => set(k, 6));
    dice = 3;
    flat = flat === 2 ? 4 : flat === 3 ? 6 : flat;
    for (const name of pet.specializations) {
      const rule = SPECIALIZATIONS[norm(name)];
      if (rule) {
        addMods(rule.mods);
        Object.entries(rule.set || {}).forEach(([k, r]) => set(k, r));
        Object.entries(rule.bump || {}).forEach(([k, r]) => bump(k, r));
      }
      const info = specializationInfo(name, data);
      specs.push({ name, text: info?.text || null, url: info?.url || null, known: !!rule });
    }
  }

  // AC — barding replaces unarmored defense when worn, and caps Dex.
  const barding = pet.barding || BARDING.none;
  const acRank = barding.key === "none" ? ranks.unarmored : ranks.barding;
  const acDex = Math.min(mods.dex, barding.dexCap);
  const ac = 10 + level + acRank + acDex + barding.ac;

  const hp = base.baseHp + level * (6 + mods.con);

  const stat = (key, ab) => ({
    key,
    rank: ranks[key] || 0,
    rankName: rankName(ranks[key] || 0),
    total: level + (ranks[key] || 0) + mods[ab],
  });

  const strikes = (base.strikes || []).map((s) => {
    const finesse = s.traits.includes("finesse");
    const die = (s.damage || "1d6").split("d")[1] || "6";
    const bonus = mods.str + flat;
    return {
      name: s.name,
      range: s.range,
      traits: [...s.traits, ...(magical ? ["magical"] : [])],
      attack: level + (ranks.unarmed || 0) + (finesse ? Math.max(mods.str, mods.dex) : mods.str),
      damage: `${dice}d${die}${bonus ? ` ${sign(bonus)}` : ""}`,
      type: s.type,
    };
  });

  const skills = Object.keys(skillAb())
    .filter((k) => ranks[k] > 0)
    .map((k) => stat(k, skillAb()[k]))
    .sort((a, b) => a.key.localeCompare(b.key));

  const speeds = Object.entries(base.speeds || {})
    .filter(([k]) => k !== "max")
    .map(([k, v]) => ({ label: k === "land" ? "speed" : k, value: Math.max(5, v + barding.speed) }))
    .sort((a, b) => (a.label === "speed" ? -1 : b.label === "speed" ? 1 : a.label.localeCompare(b.label)));

  return {
    species: base.name,
    name: pet.name,
    tier: pet.tier,
    level,
    size,
    traits: base.traits || [],
    summary: base.summary,
    mods,
    ranks,
    ac,
    acNote: barding.key === "none" ? null : `incl. ${barding.label} ${sign(barding.ac)}`,
    hp,
    perception: stat("perception", "wis"),
    saves: [stat("fortitude", "con"), stat("reflex", "dex"), stat("will", "wis")],
    skills,
    strikes,
    speeds,
    senses: base.senses,
    barding,
    checkPenalty: barding.check,
    specializations: specs,
    support: base.support,
    advanced: base.advanced,
    special: base.special,
    mount: base.mount,
    url: base.url,
  };
}

/* Convenience for callers that just have a pet + the owner's level: resolves
 * the base stat block from the loaded data itself. */
export function statblockFor(pet, pcLevel, data = _cache) {
  const base = companionBase(pet?.species, data);
  return companionStatblock(pet, base, pcLevel, data);
}
